version: '2'
services:
  db:
    image: postgres
    volumes:
      - ./docker/init-dbs.sh:/docker-entrypoint-initdb.d/init-dbs.sh
      - ./docker/volumes/pgdata:/var/lib/postgresql/data:rw
  web:
    build: .
    volumes:
      - .:/flashcardbot
    ports:
      - "3000:3000"
    depends_on:
      - db
